### PR TITLE
fated items are added

### PR DESCRIPTION
**Pull request by szabokacsa**
The calculation of some fated item failed because the item type is not specified.
Specify the item type to the proper behavior or do the lazy way below:

try to find item based on GetUniqueAccessoryOverview API
if failed try to find item based on GetUniqueWeaponOverview API
if failed try to find item based on GetUniqueArmourOverview API
if failed return error

### CODE REVIEW

**Comment by thisismydesign** [comment]
It should already work like that if you add those APIs to the item config

**Comment by thisismydesign** [comment]
When the prophecy triggers on maps you can also add the map to the compare fields. Maps can be expensive too.

**Comment by szabokacsa** [comment]
We don't know yet how poe.ninja will handle maps on 3.9 league. Because in 3.9 there are lot of tier version of a single map. I thinkg we should wait with this enhancement.

**Comment by thisismydesign** [comment]
Looks good but you should clean up this PR, it has merge conflicts and somehow it contains changes that i made.

**Pull request merged**
